title: I don't know
email: me@wokalski.com
description: > # this means to ignore newlines until "baseurl:"
    Writing about software and things. Mostly iOS/Mac related
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wokalski.com" # the base hostname & protocol for your site
twitter_username: wokalski
github_username:  wokalski
permalink: /:title/

# Build settings
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
